v2
grupyrp/caipyra2017 pull request #14
Opened 2017-05-06 22:55 UTC by leoberdu

New version.

2017-05-06 23:09 UTC, daneoshiga commented on CNAME
> -caipyra.python.org.br
precisa desse arquivo não?

2017-05-06 23:23 UTC, daneoshiga requested changes
restaura o CNAME ali

2017-05-07 15:21 UTC, leoberdu commented
Feito @daneoshiga.

2017-05-08 02:03 UTC, merged

2017-05-08 02:03 UTC, daneoshiga commented
teje merjado